INSERT INTO regions (code, name) VALUES
('CL-AP', 'Arica y Parinacota'),
('CL-TA', 'Tarapacá'),
('CL-AN', 'Antofagasta'),
('CL-AT', 'Atacama'),
('CL-CO', 'Coquimbo'),
('CL-VS', 'Valparaíso'),
('CL-RM', 'Metropolitana de Santiago'),
('CL-LI', 'Libertador General Bernardo O''Higgins'),
('CL-ML', 'Maule'),
('CL-NB', 'Ñuble'),
('CL-BI', 'Biobío'),
('CL-AR', 'La Araucanía'),
('CL-LR', 'Los Ríos'),
('CL-LL', 'Los Lagos'),
('CL-AI', 'Aysén del General Carlos Ibáñez del Campo'),
('CL-MA', 'Magallanes y de la Antártica Chilena');

INSERT INTO communes (region_id, code, name) VALUES
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-ARI', 'Arica'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-CAM', 'Camarones'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-PGE', 'General Lagos'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-PUT', 'Putre'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-ACN', 'Arica Norte'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-ACS', 'Arica Sur'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-AZP', 'Azapa'),
((SELECT id FROM regions WHERE code = 'CL-AP'), 'AP-LLU', 'Lluta'),

((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-IQQ', 'Iquique'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-AHO', 'Alto Hospicio'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-POZ', 'Pozo Almonte'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-PIC', 'Pica'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-HUA', 'Huara'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-CAM', 'Camiña'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-COL', 'Colchane'),
((SELECT id FROM regions WHERE code = 'CL-TA'), 'TA-MAT', 'Mamiña'),

((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-ANT', 'Antofagasta'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-MAR', 'Mejillones'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-SPE', 'Sierra Gorda'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-TAL', 'Taltal'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-CAL', 'Calama'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-OLL', 'Ollagüe'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-SPA', 'San Pedro de Atacama'),
((SELECT id FROM regions WHERE code = 'CL-AN'), 'AN-TOC', 'Tocopilla'),

((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-COP', 'Copiapó'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-CAL', 'Caldera'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-TIE', 'Tierra Amarilla'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-CHA', 'Chañaral'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-DIE', 'Diego de Almagro'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-VLL', 'Vallenar'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-ALT', 'Alto del Carmen'),
((SELECT id FROM regions WHERE code = 'CL-AT'), 'AT-HUA', 'Huasco'),

((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-LSE', 'La Serena'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-COQ', 'Coquimbo'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-AND', 'Andacollo'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-VIC', 'Vicuña'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-ILL', 'Illapel'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-SAL', 'Salamanca'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-OVA', 'Ovalle'),
((SELECT id FROM regions WHERE code = 'CL-CO'), 'CO-MON', 'Monte Patria'),

((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-VPA', 'Valparaíso'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-VIN', 'Viña del Mar'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-CON', 'Concón'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-QUI', 'Quilpué'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-VAL', 'Villa Alemana'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-SAN', 'San Antonio'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-QUI2', 'Quillota'),
((SELECT id FROM regions WHERE code = 'CL-VS'), 'VS-LCA', 'La Calera'),

((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-STG', 'Santiago'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-PRO', 'Providencia'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-LCO', 'Las Condes'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-NUN', 'Ñuñoa'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-MAI', 'Maipú'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-PUD', 'Pudahuel'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-PEN', 'Puente Alto'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-SJB', 'San Joaquín'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-EST', 'Estación Central'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-LFL', 'La Florida'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-LRN', 'La Reina'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-IND', 'Independencia'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-REN', 'Renca'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-CER', 'Cerrillos'),
((SELECT id FROM regions WHERE code = 'CL-RM'), 'RM-SMI', 'San Miguel'),

((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-RAN', 'Rancagua'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-MAC', 'Machalí'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-GRA', 'Graneros'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-SFE', 'San Fernando'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-CHI', 'Chimbarongo'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-SCR', 'Santa Cruz'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-PEU', 'Peumo'),
((SELECT id FROM regions WHERE code = 'CL-LI'), 'LI-REN', 'Rengo'),

((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-TAL', 'Talca'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-CUR', 'Curicó'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-LIN', 'Linares'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-CST', 'Constitución'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-MOL', 'Molina'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-SCL', 'San Clemente'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-PAR', 'Parral'),
((SELECT id FROM regions WHERE code = 'CL-ML'), 'ML-CAU', 'Cauquenes'),

((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-CHI', 'Chillán'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-CHV', 'Chillán Viejo'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-SCA', 'San Carlos'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-BUL', 'Bulnes'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-QUI', 'Quirihue'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-COE', 'Coelemu'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-YUN', 'Yungay'),
((SELECT id FROM regions WHERE code = 'CL-NB'), 'NB-NIN', 'Ninhue'),

((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-CON', 'Concepción'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-TAL', 'Talcahuano'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-HUA', 'Hualpén'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-CHI', 'Chiguayante'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-SPE', 'San Pedro de la Paz'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-COR', 'Coronel'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-LAN', 'Los Ángeles'),
((SELECT id FROM regions WHERE code = 'CL-BI'), 'BI-TOM', 'Tomé'),

((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-TEM', 'Temuco'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-PAD', 'Padre Las Casas'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-VIL', 'Villarrica'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-PUC', 'Pucón'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-ANG', 'Angol'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-LAU', 'Lautaro'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-VIC', 'Victoria'),
((SELECT id FROM regions WHERE code = 'CL-AR'), 'AR-NVA', 'Nueva Imperial'),

((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-VAL', 'Valdivia'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-PAI', 'Paillaco'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-LUN', 'Lanco'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-MAF', 'Máfil'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-LUN2', 'La Unión'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-RIB', 'Río Bueno'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-MAR', 'Mariquina'),
((SELECT id FROM regions WHERE code = 'CL-LR'), 'LR-LAG', 'Los Lagos'),

((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-PMO', 'Puerto Montt'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-OSO', 'Osorno'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-CAS', 'Castro'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-ANC', 'Ancud'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-CAL', 'Calbuco'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-PVA', 'Puerto Varas'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-LLA', 'Llanquihue'),
((SELECT id FROM regions WHERE code = 'CL-LL'), 'LL-QUE', 'Quellón'),

((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-COY', 'Coyhaique'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-PAY', 'Puerto Aysén'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-CHC', 'Chile Chico'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-CIS', 'Cisnes'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-RIB', 'Río Ibáñez'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-OGA', 'O''Higgins'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-TOR', 'Tortel'),
((SELECT id FROM regions WHERE code = 'CL-AI'), 'AI-GUA', 'Guaitecas'),

((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-PAQ', 'Punta Arenas'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-NAT', 'Natales'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-POR', 'Porvenir'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-CAB', 'Cabo de Hornos'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-LAG', 'Laguna Blanca'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-RVE', 'Río Verde'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-PRI', 'Primavera'),
((SELECT id FROM regions WHERE code = 'CL-MA'), 'MA-TDL', 'Timaukel');

INSERT INTO sectors (code, name) VALUES
('SEC_TI', 'Tecnologías de la Información'),
('SEC_EDU', 'Educación'),
('SEC_PUBLICO', 'Sector Público'),
('SEC_SALUD', 'Salud'),
('SEC_COMERCIAL', 'Comercio y Ventas'),
('SEC_LOGISTICA', 'Logística y Transporte'),
('SEC_CONSTRUCCION', 'Construcción e Infraestructura'),
('SEC_ADMIN_FIN', 'Administración y Finanzas'),
('SEC_INDUSTRIA', 'Manufactura e Industria'),
('SEC_SERVICIOS', 'Atención al Cliente y Servicios');

INSERT INTO skills (code, name) VALUES
('SK_TI_DESARROLLO_SW', 'Desarrollo de software'),
('SK_TI_TESTING_QA', 'Testing y QA'),
('SK_TI_BASES_DATOS', 'Bases de datos'),
('SK_TI_APIS_REST', 'Integración de APIs REST'),
('SK_TI_CONTROL_VERSIONES', 'Control de versiones'),
('SK_TI_METODOLOGIAS_AGILES', 'Metodologías ágiles'),
('SK_TI_ANALISIS_REQ', 'Análisis de requerimientos'),
('SK_TI_UX_UI', 'Diseño UX/UI'),
('SK_TI_SEGURIDAD_APP', 'Seguridad de aplicaciones'),
('SK_TI_CLOUD_DEVOPS', 'Cloud y DevOps'),
('SK_TI_SOPO_TECNICO', 'Soporte técnico'),
('SK_TI_DOCUMENTACION', 'Documentación técnica'),
('SK_TI_GESTION_INCIDENTES', 'Gestión de incidentes'),
('SK_TI_MONITOREO', 'Monitoreo de sistemas'),
('SK_TI_AUTOMATIZACION', 'Automatización de procesos TI'),

('SK_EDU_PLANIF_CLASES', 'Planificación de clases'),
('SK_EDU_GESTION_AULA', 'Gestión de aula'),
('SK_EDU_EVAL_APRENDIZAJE', 'Evaluación de aprendizajes'),
('SK_EDU_DISENO_CURRICULAR', 'Diseño curricular'),
('SK_EDU_DIDACTICA_ACTIVA', 'Didácticas activas'),
('SK_EDU_INCLUSION_EDUCATIVA', 'Inclusión educativa'),
('SK_EDU_TECH_EDUCATIVA', 'Tecnología educativa'),
('SK_EDU_COMUNICACION_APODERADOS', 'Comunicación con apoderados'),
('SK_EDU_TUTORIA', 'Tutoría y acompañamiento'),
('SK_EDU_MEDIACION_CONFLICTOS', 'Mediación de conflictos escolares'),
('SK_EDU_GESTION_EVALUACIONES', 'Gestión de evaluaciones'),
('SK_EDU_TRABAJO_COLABORATIVO', 'Trabajo colaborativo docente'),
('SK_EDU_ORIENTACION_ESTUDIANTIL', 'Orientación estudiantil'),
('SK_EDU_GESTION_PROYECTOS', 'Gestión de proyectos educativos'),
('SK_EDU_MEJORA_CONTINUA', 'Mejora continua educativa'),

('SK_PUB_NORMATIVA', 'Gestión normativa'),
('SK_PUB_TRAMITACION', 'Tramitación administrativa'),
('SK_PUB_TRANSPARENCIA', 'Transparencia y probidad'),
('SK_PUB_ATENCION_CIUDADANA', 'Atención ciudadana'),
('SK_PUB_REDACCION_OFICIAL', 'Redacción de documentos oficiales'),
('SK_PUB_GESTION_ARCHIVOS', 'Gestión documental y archivos'),
('SK_PUB_PLANIFICACION_PUBLICA', 'Planificación pública'),
('SK_PUB_CONTROL_GESTION', 'Control de gestión pública'),
('SK_PUB_COMPRAS_PUBLICAS', 'Compras públicas'),
('SK_PUB_GESTION_CONVENIOS', 'Gestión de convenios'),
('SK_PUB_PRESUP_PUBLICO', 'Presupuesto público'),
('SK_PUB_ANALISIS_DATOS', 'Análisis de datos para gestión pública'),
('SK_PUB_COORD_INTERINSTIT', 'Coordinación interinstitucional'),
('SK_PUB_GESTION_PROYECTOS', 'Gestión de proyectos públicos'),
('SK_PUB_CUMPLIMIENTO', 'Cumplimiento regulatorio'),

('SK_SALUD_ATENCION_PACIENTE', 'Atención de pacientes'),
('SK_SALUD_REGISTRO_CLINICO', 'Registro clínico'),
('SK_SALUD_CONTROL_SIGNOS', 'Control de signos vitales'),
('SK_SALUD_ADMIN_MED', 'Administración de medicamentos'),
('SK_SALUD_PREV_INFECCIONES', 'Prevención de infecciones'),
('SK_SALUD_TRIAGE', 'Triage y priorización'),
('SK_SALUD_EDUCACION_PACIENTE', 'Educación al paciente'),
('SK_SALUD_TRABAJO_INTERDISC', 'Trabajo interdisciplinario'),
('SK_SALUD_GESTION_AGENDA', 'Gestión de agenda clínica'),
('SK_SALUD_APOYO_DIAGNOSTICO', 'Apoyo en diagnóstico'),
('SK_SALUD_SEGURIDAD_PACIENTE', 'Seguridad del paciente'),
('SK_SALUD_DERIVACION', 'Derivación asistencial'),
('SK_SALUD_ETICA', 'Ética clínica'),
('SK_SALUD_CUMPL_PROTOCOLOS', 'Cumplimiento de protocolos'),
('SK_SALUD_GESTION_URGENCIAS', 'Gestión de urgencias'),

('SK_COM_VENTA_CONSULTIVA', 'Venta consultiva'),
('SK_COM_NEGOCIACION', 'Negociación comercial'),
('SK_COM_PROSPECCION', 'Prospección de clientes'),
('SK_COM_CIERRE_VENTAS', 'Cierre de ventas'),
('SK_COM_GESTION_CARTERA', 'Gestión de cartera'),
('SK_COM_CRM', 'Manejo de CRM'),
('SK_COM_MERCHANDISING', 'Merchandising'),
('SK_COM_ATENCION_PUNTO_VENTA', 'Atención en punto de venta'),
('SK_COM_GESTION_STOCK', 'Gestión de stock comercial'),
('SK_COM_ANALISIS_VENTAS', 'Análisis de ventas'),
('SK_COM_POSTVENTA', 'Postventa'),
('SK_COM_ECOMMERCE', 'Operación de e-commerce'),
('SK_COM_MARKETING_PROMO', 'Marketing promocional'),
('SK_COM_PLAN_COMERCIAL', 'Planificación comercial'),
('SK_COM_METAS_KPI', 'Gestión de metas y KPI comerciales'),

('SK_LOG_PLAN_RUTAS', 'Planificación de rutas'),
('SK_LOG_GESTION_BODEGA', 'Gestión de bodega'),
('SK_LOG_CONTROL_INVENTARIO', 'Control de inventario'),
('SK_LOG_COORD_DESPACHOS', 'Coordinación de despachos'),
('SK_LOG_TRAZABILIDAD', 'Trazabilidad de envíos'),
('SK_LOG_LOG_INVERSA', 'Logística inversa'),
('SK_LOG_NORMATIVA_TRANSP', 'Normativa de transporte'),
('SK_LOG_GESTION_FLOTA', 'Gestión de flota'),
('SK_LOG_OPT_COSTOS', 'Optimización de costos logísticos'),
('SK_LOG_DOCUMENTACION', 'Documentación de transporte'),
('SK_LOG_SEGURIDAD_CARGA', 'Seguridad de carga'),
('SK_LOG_WMS', 'Uso de sistemas WMS'),
('SK_LOG_MANTENCION_BASICA', 'Mantención básica de equipos'),
('SK_LOG_GESTION_TIEMPOS', 'Gestión de tiempos de entrega'),
('SK_LOG_COORD_PROVEEDORES', 'Coordinación con proveedores'),

('SK_CON_LECTURA_PLANOS', 'Lectura de planos'),
('SK_CON_METRADOS', 'Metrados y cubicaciones'),
('SK_CON_SUPERVISION_OBRA', 'Supervisión de obra'),
('SK_CON_PREV_RIESGOS', 'Prevención de riesgos en obra'),
('SK_CON_CONTROL_CALIDAD', 'Control de calidad constructiva'),
('SK_CON_PROGRAMACION_OBRA', 'Programación de obra'),
('SK_CON_COTIZACIONES', 'Gestión de cotizaciones'),
('SK_CON_PRESUPUESTOS', 'Presupuestos de construcción'),
('SK_CON_COORD_CONTRATISTAS', 'Coordinación de contratistas'),
('SK_CON_GESTION_MATERIALES', 'Gestión de materiales'),
('SK_CON_NORMATIVA_TECNICA', 'Normativa técnica de construcción'),
('SK_CON_CAD_BIM_BASICO', 'CAD/BIM básico'),
('SK_CON_INSPECCIONES', 'Inspecciones técnicas'),
('SK_CON_GESTION_PERMISOS', 'Gestión de permisos'),
('SK_CON_CIERRE_PROYECTO', 'Cierre de proyectos de obra'),

('SK_AF_CONTABILIDAD', 'Contabilidad general'),
('SK_AF_ANALISIS_FINANCIERO', 'Análisis financiero'),
('SK_AF_PRESUPUESTACION', 'Presupuestación'),
('SK_AF_TESORERIA', 'Tesorería'),
('SK_AF_FACTURACION', 'Facturación'),
('SK_AF_CONCILIACION_BANCARIA', 'Conciliación bancaria'),
('SK_AF_REMUNERACIONES', 'Gestión de remuneraciones'),
('SK_AF_TRIBUTACION', 'Tributación'),
('SK_AF_CONTROL_GESTION', 'Control de gestión'),
('SK_AF_COSTOS', 'Análisis de costos'),
('SK_AF_EXCEL_AVANZADO', 'Excel avanzado'),
('SK_AF_ERP', 'Uso de ERP administrativo'),
('SK_AF_AUDITORIA_INTERNA', 'Auditoría interna'),
('SK_AF_GESTION_DOC', 'Gestión documental administrativa'),
('SK_AF_PLAN_FINANCIERA', 'Planificación financiera'),

('SK_IND_OPERACION_MAQUINAS', 'Operación de maquinaria'),
('SK_IND_MANTENCION', 'Mantención industrial'),
('SK_IND_CONTROL_PROCESOS', 'Control de procesos productivos'),
('SK_IND_CONTROL_CALIDAD', 'Control de calidad industrial'),
('SK_IND_SEGURIDAD_INDUSTRIAL', 'Seguridad industrial'),
('SK_IND_MEJORA_CONTINUA', 'Mejora continua'),
('SK_IND_LEAN_BASICO', 'Lean manufacturing básico'),
('SK_IND_GESTION_PRODUCCION', 'Gestión de producción'),
('SK_IND_PLAN_MANTENCION', 'Planificación de mantención'),
('SK_IND_OPERACION_LINEA', 'Operación de línea'),
('SK_IND_LECTURA_PLANOS', 'Lectura de planos industriales'),
('SK_IND_GESTION_INSUMOS', 'Gestión de insumos'),
('SK_IND_TRAZABILIDAD', 'Trazabilidad de producción'),
('SK_IND_CUMPL_NORMAS', 'Cumplimiento de normas técnicas'),
('SK_IND_REPORTE_PRODUCCION', 'Reporte de producción'),

('SK_SERV_ATENCION_CLIENTE', 'Atención al cliente'),
('SK_SERV_COMUNICACION', 'Comunicación efectiva'),
('SK_SERV_RESOLUCION_PROBLEMAS', 'Resolución de problemas'),
('SK_SERV_GESTION_RECLAMOS', 'Gestión de reclamos'),
('SK_SERV_VENTA_ASISTIDA', 'Venta asistida'),
('SK_SERV_PROCESO_CAJA', 'Proceso de caja'),
('SK_SERV_AGENDAMIENTO', 'Agendamiento de servicios'),
('SK_SERV_SEGUIMIENTO_CASOS', 'Seguimiento de casos'),
('SK_SERV_PROTOCOL_SERVICIO', 'Protocolos de servicio'),
('SK_SERV_HERRAMIENTAS_DIG', 'Uso de herramientas digitales de atención'),
('SK_SERV_POSTVENTA', 'Atención postventa'),
('SK_SERV_CALIDAD_SERVICIO', 'Control de calidad de servicio'),
('SK_SERV_TRABAJO_EQUIPO', 'Trabajo en equipo'),
('SK_SERV_GESTION_TIEMPO', 'Gestión del tiempo'),
('SK_SERV_ORIENTACION_RESULT', 'Orientación a resultados');

INSERT INTO sector_skills (sector_id, skill_id)
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_TI' AND sk.code IN (
'SK_TI_DESARROLLO_SW','SK_TI_TESTING_QA','SK_TI_BASES_DATOS','SK_TI_APIS_REST','SK_TI_CONTROL_VERSIONES',
'SK_TI_METODOLOGIAS_AGILES','SK_TI_ANALISIS_REQ','SK_TI_UX_UI','SK_TI_SEGURIDAD_APP','SK_TI_CLOUD_DEVOPS',
'SK_TI_SOPO_TECNICO','SK_TI_DOCUMENTACION','SK_TI_GESTION_INCIDENTES','SK_TI_MONITOREO','SK_TI_AUTOMATIZACION'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_EDU' AND sk.code IN (
'SK_EDU_PLANIF_CLASES','SK_EDU_GESTION_AULA','SK_EDU_EVAL_APRENDIZAJE','SK_EDU_DISENO_CURRICULAR','SK_EDU_DIDACTICA_ACTIVA',
'SK_EDU_INCLUSION_EDUCATIVA','SK_EDU_TECH_EDUCATIVA','SK_EDU_COMUNICACION_APODERADOS','SK_EDU_TUTORIA','SK_EDU_MEDIACION_CONFLICTOS',
'SK_EDU_GESTION_EVALUACIONES','SK_EDU_TRABAJO_COLABORATIVO','SK_EDU_ORIENTACION_ESTUDIANTIL','SK_EDU_GESTION_PROYECTOS','SK_EDU_MEJORA_CONTINUA'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_PUBLICO' AND sk.code IN (
'SK_PUB_NORMATIVA','SK_PUB_TRAMITACION','SK_PUB_TRANSPARENCIA','SK_PUB_ATENCION_CIUDADANA','SK_PUB_REDACCION_OFICIAL',
'SK_PUB_GESTION_ARCHIVOS','SK_PUB_PLANIFICACION_PUBLICA','SK_PUB_CONTROL_GESTION','SK_PUB_COMPRAS_PUBLICAS','SK_PUB_GESTION_CONVENIOS',
'SK_PUB_PRESUP_PUBLICO','SK_PUB_ANALISIS_DATOS','SK_PUB_COORD_INTERINSTIT','SK_PUB_GESTION_PROYECTOS','SK_PUB_CUMPLIMIENTO'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_SALUD' AND sk.code IN (
'SK_SALUD_ATENCION_PACIENTE','SK_SALUD_REGISTRO_CLINICO','SK_SALUD_CONTROL_SIGNOS','SK_SALUD_ADMIN_MED','SK_SALUD_PREV_INFECCIONES',
'SK_SALUD_TRIAGE','SK_SALUD_EDUCACION_PACIENTE','SK_SALUD_TRABAJO_INTERDISC','SK_SALUD_GESTION_AGENDA','SK_SALUD_APOYO_DIAGNOSTICO',
'SK_SALUD_SEGURIDAD_PACIENTE','SK_SALUD_DERIVACION','SK_SALUD_ETICA','SK_SALUD_CUMPL_PROTOCOLOS','SK_SALUD_GESTION_URGENCIAS'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_COMERCIAL' AND sk.code IN (
'SK_COM_VENTA_CONSULTIVA','SK_COM_NEGOCIACION','SK_COM_PROSPECCION','SK_COM_CIERRE_VENTAS','SK_COM_GESTION_CARTERA',
'SK_COM_CRM','SK_COM_MERCHANDISING','SK_COM_ATENCION_PUNTO_VENTA','SK_COM_GESTION_STOCK','SK_COM_ANALISIS_VENTAS',
'SK_COM_POSTVENTA','SK_COM_ECOMMERCE','SK_COM_MARKETING_PROMO','SK_COM_PLAN_COMERCIAL','SK_COM_METAS_KPI'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_LOGISTICA' AND sk.code IN (
'SK_LOG_PLAN_RUTAS','SK_LOG_GESTION_BODEGA','SK_LOG_CONTROL_INVENTARIO','SK_LOG_COORD_DESPACHOS','SK_LOG_TRAZABILIDAD',
'SK_LOG_LOG_INVERSA','SK_LOG_NORMATIVA_TRANSP','SK_LOG_GESTION_FLOTA','SK_LOG_OPT_COSTOS','SK_LOG_DOCUMENTACION',
'SK_LOG_SEGURIDAD_CARGA','SK_LOG_WMS','SK_LOG_MANTENCION_BASICA','SK_LOG_GESTION_TIEMPOS','SK_LOG_COORD_PROVEEDORES'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_CONSTRUCCION' AND sk.code IN (
'SK_CON_LECTURA_PLANOS','SK_CON_METRADOS','SK_CON_SUPERVISION_OBRA','SK_CON_PREV_RIESGOS','SK_CON_CONTROL_CALIDAD',
'SK_CON_PROGRAMACION_OBRA','SK_CON_COTIZACIONES','SK_CON_PRESUPUESTOS','SK_CON_COORD_CONTRATISTAS','SK_CON_GESTION_MATERIALES',
'SK_CON_NORMATIVA_TECNICA','SK_CON_CAD_BIM_BASICO','SK_CON_INSPECCIONES','SK_CON_GESTION_PERMISOS','SK_CON_CIERRE_PROYECTO'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_ADMIN_FIN' AND sk.code IN (
'SK_AF_CONTABILIDAD','SK_AF_ANALISIS_FINANCIERO','SK_AF_PRESUPUESTACION','SK_AF_TESORERIA','SK_AF_FACTURACION',
'SK_AF_CONCILIACION_BANCARIA','SK_AF_REMUNERACIONES','SK_AF_TRIBUTACION','SK_AF_CONTROL_GESTION','SK_AF_COSTOS',
'SK_AF_EXCEL_AVANZADO','SK_AF_ERP','SK_AF_AUDITORIA_INTERNA','SK_AF_GESTION_DOC','SK_AF_PLAN_FINANCIERA'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_INDUSTRIA' AND sk.code IN (
'SK_IND_OPERACION_MAQUINAS','SK_IND_MANTENCION','SK_IND_CONTROL_PROCESOS','SK_IND_CONTROL_CALIDAD','SK_IND_SEGURIDAD_INDUSTRIAL',
'SK_IND_MEJORA_CONTINUA','SK_IND_LEAN_BASICO','SK_IND_GESTION_PRODUCCION','SK_IND_PLAN_MANTENCION','SK_IND_OPERACION_LINEA',
'SK_IND_LECTURA_PLANOS','SK_IND_GESTION_INSUMOS','SK_IND_TRAZABILIDAD','SK_IND_CUMPL_NORMAS','SK_IND_REPORTE_PRODUCCION'
)
UNION ALL
SELECT s.id, sk.id FROM sectors s JOIN skills sk ON s.code = 'SEC_SERVICIOS' AND sk.code IN (
'SK_SERV_ATENCION_CLIENTE','SK_SERV_COMUNICACION','SK_SERV_RESOLUCION_PROBLEMAS','SK_SERV_GESTION_RECLAMOS','SK_SERV_VENTA_ASISTIDA',
'SK_SERV_PROCESO_CAJA','SK_SERV_AGENDAMIENTO','SK_SERV_SEGUIMIENTO_CASOS','SK_SERV_PROTOCOL_SERVICIO','SK_SERV_HERRAMIENTAS_DIG',
'SK_SERV_POSTVENTA','SK_SERV_CALIDAD_SERVICIO','SK_SERV_TRABAJO_EQUIPO','SK_SERV_GESTION_TIEMPO','SK_SERV_ORIENTACION_RESULT'
);
