SET @db := DATABASE();

SET @cnt := (SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = @db AND TABLE_NAME = 'jobs' AND COLUMN_NAME = 'requirements');
SET @stmt := IF(@cnt > 0, 'ALTER TABLE jobs DROP COLUMN requirements', 'SELECT 1');
PREPARE p FROM @stmt; EXECUTE p; DEALLOCATE PREPARE p;
