server.port=8080
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/worksi?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:worksi}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:worksi}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
